services:
  db:
    image: postgres
    container_name: liven-database
    environment:
      POSTGRES_DB: liven-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
